# config file with file paths and other stuff that would be computer-dependant
orca_path: /opt/womble/orca/orca_5.0.0/orca
gap_fit_path: /opt/womble/QUIP/2021_07_06//bin/gap_fit
quip_path: /opt/womble/QUIP/2021_07_06//linux_x86_64_gfortran_openmp/quip
ace_fit_path: julia /home/eg475/.julia/dev/ACE1pack/scripts/ace_fit.jl

scratch_path: /scratch-ssd/eg475
tmp_dir: /tmp/eg475

dftb_param_path: /home/eg475/scripts/source_files/tightbind.parms.DFTB.mio-0-1.xml
glue_fname: /home/eg475/scripts/source_files/glue_repulsive_fitted.xml
isolated_atoms_fname: /home/eg475/scripts/source_files/isolated_atoms.xyz

util_root: /home/eg475/scripts/util/
julia_2b_script: /home/eg475/scripts/julia_scripts/2b.jl




